apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
    haproxy.router.openshift.io/timeout: 120s
  labels:
    app.kubernetes.io/instance: model-deploy
    component: predictor
    opendatahub.io/dashboard: "true"
    serving.kserve.io/inferenceservice: edge-inference
  name: edge-inference-predictor
  namespace: model-deploy
spec:
  host: edge-inference-predictor-model-deploy.apps.singlenodeopenshift.acic.local
  port:
    targetPort: http1
  to:
    kind: Service
    name: edge-inference-predictor
    weight: 100
  wildcardPolicy: None