apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '1'
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '[]'
    opendatahub.io/template-display-name: vLLM ServingRuntime for KServe CPU
    opendatahub.io/template-name: vllm-runtime-cpu
    openshift.io/display-name: vLLM-CPU
  name: vllm-cpu
  namespace: model-deploy
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  builtInAdapter:
    modelLoadingTimeoutMillis: 90000
  containers:
    - command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: VLLM_CPU_KVCACHE_SPACE
          value: '2'
        - name: OMP_NUM_THREADS
          value: '1'
        - name: VLLM_CPU_OMP_THREADS_BIND
          value: all
      image: 'quay.io/rh-aiservices-bu/rhoai-lab-insurance-claim-vllm-cpu:v0.9.1'
      name: kserve-container
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
