apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: cluster-collector
  namespace: opendatahub-edge-collector
  labels:
    app.kubernetes.io/managed-by: opentelemetry-operator
spec:
  mode: deployment
  observability:
    metrics:
      enableMetrics: true
  env:
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              job_name: model-metrics
              metrics_path: /metrics
              scrape_interval: 5s
              static_configs:
                - targets:
                    - edge-inference-predictor-model-deploy.apps.singlenodeopenshift.acic.local
    exporters:
      prometheusremotewrite/core:
        endpoint: "https://observatorium-api-open-cluster-management-observability.apps.baremetal2.acic.local/api/v1/receive"
        tls:
          insecure: true
    processors:
      batch:
        send_batch_size: 10000
        timeout: 1s
    service:
      pipelines:
        metrics:
          receivers:
            - prometheus
          processors:
            - batch
          exporters:
            - prometheusremotewrite/core
