apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: cluster-collector
  namespace: opendatahub-edge-collector
spec:
  mode: deployment
  observability:
    metrics:
      enableMetrics: true

  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: model-metrics
              metrics_path: /metrics
              scrape_interval: 5s
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              static_configs:
                - targets:
                    - edge-inference-predictor-model-deploy.apps.singlenodeopenshift.acic.local

    processors:
      batch:
        timeout: 5s
        send_batch_size: 1000
      attributes:
        actions:
          - key: source
            value: "edge-collector"
            action: insert

    exporters:
      prometheusremotewrite:
        endpoint: "https://observatorium-api-open-cluster-management-observability.apps.baremetal2.acic.local/api/metrics/v1/default/api/v1/receive"

        auth:
          authenticator: bearertokenauth

        tls:
          cert_file: /etc/otel/certs/client.crt
          key_file: /etc/otel/certs/client.key
          ca_file: /etc/otel/certs/ca.crt
          insecure: true
          insecure_skip_verify: true

      debug:
        verbosity: detailed

    extensions:
      bearertokenauth:
        token: "/var/run/secrets/kubernetes.io/serviceaccount/token"

    service:
      extensions: [bearertokenauth]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [attributes, batch]
          exporters: [prometheusremotewrite, debug]
