apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: open-cluster-management-addon-observability
spec:
  mode: deployment
  replicas: 1
  volumes:
    - name: mco-ca
      secret:
        secretName: observability-managed-cluster-certs
    - name: mco-certs
      secret:
        secretName: observability-controller-open-cluster-management.io-observability-signer-client-cert
  volumeMounts:
    - name: mco-ca
      mountPath: /etc/mco/ca
    - name: mco-certs
      mountPath: /etc/mco/certs

  config:
    receivers:
      # REQUIRED - o il pipeline va in errore
      otlp:
        protocols:
          grpc: {}
          http: {}

      # Prometheus scrape da Thanos
      prometheus:
        config:
          scrape_configs:
            - job_name: thanos
              scrape_interval: 5s
              scheme: https
              static_configs:
                - targets:
                    - "thanos-querier.openshift-monitoring.svc.cluster.local:9091/metrics"
              tls_config:
                insecure_skip_verify: true

    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 25
      resource:
        attributes:
          - key: source
            value: rhde
            action: insert
          - key: process.executable.path
            action: delete
          - key: process.command
            action: delete
          - key: process.command_line
            action: delete

    exporters:
      debug:
        verbosity: detailed
      prometheusremotewrite:
        endpoint: https://observatorium-api-open-cluster-management-observability.apps.baremetal2.acic.local/api/metrics/v1/default/api/v1/receive
        tls:
          cert_file: /etc/mco/certs/tls.crt
          key_file: /etc/mco/certs/tls.key
          ca_file: /etc/mco/ca/ca.crt
        resource_to_telemetry_conversion:
          enabled: true

    service:
      pipelines:
        metrics:
          receivers:
            - otlp
            - prometheus
          processors:
            - memory_limiter
            - resource
            - batch
          exporters:
            - debug
            - prometheusremotewrite
